### ISSUE TITLE
[PE-D][Tester B] Unable to add class at midnight

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W13-3/tp#135]
The timetable does not allow me to add a class at midnight (t = 0). 
![image.png](https://raw.githubusercontent.com/Leong-ZM/ped/main/files/57c713a0-4567-445e-b4cb-1061b198cfca.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Leong-ZM/ped#3

**Comment by Heart-of-N1** [comment]
Updated UG to draw attention to the range of time allowed.
