### ISSUE TITLE
[PE-D][Tester E] adding expenditures is too complicated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W13-3/tp#139]
![image.png](https://raw.githubusercontent.com/samuelory/ped/main/files/61fae7c3-000c-4809-b0d0-b8aa94cbb17d.png)

to add each expenditure you need to type so many other letters, maybe can reduce the length of each command like i.e. change amt/ to a/

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: samuelory/ped#6

**Comment by Mmaxx15** [comment]
no choice if at is all in 1 line
