### ISSUE TITLE
[PE-D][Tester D] Unknown fields when listing expenditures

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W13-3/tp#142]
When I list out the products, I am not sure of what the NA fields means in the list. Perhaps removing the NA fields will be better if there is no value added? 

![Screenshot 2024-04-05 at 5.01.19 PM.png](https://raw.githubusercontent.com/leongxingyu/ped/main/files/7899a161-aa82-4d33-93ba-b8251cb142f6.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: leongxingyu/ped#8

**Comment by Heart-of-N1** [comment]
NA refers to any expenditures that have no "type" contents. UG has been updated to reflect the difference between adding new expenditures with "type" and adding new expenditures without "type", where they will default to an "NA".
