### ISSUE TITLE
[PE-D][Tester D] GPA feature's error prompt seems a little out of place

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W13-3/tp#147]
Upon entering wrong GPA command for GPA calculation, the error pormpts only occur at the bottom.

Users will be unsure of which input they have keyed in wrongly and this might lead to reptitive errors and wrong GPA calculation.

![Screenshot 2024-04-05 at 4.33.55 PM.png](https://raw.githubusercontent.com/leongxingyu/ped/main/files/017bc3dc-2ce3-4f12-96b3-5eade1f7309b.png)￼

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: leongxingyu/ped#10

**Comment by Heart-of-N1** [comment]
Amended the processGPACommand method and calculatePointsForGrade method to throw timely error messages when a wrong GPA input is entered.
