### ISSUE TITLE
[PE-D][Tester D] Imcomplete UG (Timetable section)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W13-3/tp#152]
I am unsure of what to do for the timetable feature. From the Jar file, there was instructions on how to add a new class, however, there are no instructions given on how to view the classes added nor are explanation on what to do after adding a class. 

![1. Type GPA (Regardless of caps) to proceed to start the function..png](https://raw.githubusercontent.com/leongxingyu/ped/main/files/78f87d19-74dd-48bf-bf81-3d314f3cfd9a.png)￼

-------------
Labels: `severity.High` `type.DocumentationBug`
original: leongxingyu/ped#12

**Comment by Heart-of-N1** [comment]
Similiar issue to issue #168. Already added the timetable portion in the UG.
