### ISSUE TITLE
[PE-D][Tester D] Timetable storage doesn't seem to store correctly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W13-3/tp#162]
When I key in the commands to enter new classes (fig1), the storage file for timetable.txt doesnt seem to match (fig2).

![Screenshot 2024-04-05 at 5.23.25 PM.png](https://raw.githubusercontent.com/leongxingyu/ped/main/files/675039dc-3003-4137-b32c-b4e0fd1ff0eb.png)￼
fig 1

![Screenshot 2024-04-05 at 5.24.51 PM.png](https://raw.githubusercontent.com/leongxingyu/ped/main/files/5a63e69d-284f-4b10-bc6c-c2d38f2006bf.png)￼
fig 2

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: leongxingyu/ped#15

**Comment by Heart-of-N1** [comment]
Requested additional info and validation. @Mmaxx15 @nyh3 @HikoHikoHiko @Haotian199

**Comment by Heart-of-N1** [comment]
The way the program stores the timetable classes are explained in the UG.  Since we store the classes in an hourly format on each row, the above image showed a correct storing of the timetable details. Hence this is not a bug.
