### ISSUE TITLE
[PE-D][Tester C] The user guide does not show the instructions on how to use the timetable command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W13-3/tp#163]
![image.png](https://raw.githubusercontent.com/XavierLiau34/ped/main/files/522505a9-62bc-4a87-8a59-6ac653807ffa.png)

I only see the instructions when i launch the app

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: XavierLiau34/ped#5

**Comment by Heart-of-N1** [comment]
Same as issue #168. Added relevant user guide explanations for users.
