### ISSUE TITLE
[PE-D][Tester E] timetable feature is hard to use

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W13-3/tp#168]
![image.png](https://raw.githubusercontent.com/samuelory/ped/main/files/8d9205e4-c05b-4550-8cc9-70eaea869782.png)

doesnt help that the help command doesnt tell you what the format of each section should be, and the userguide timetable section is missing!!

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: samuelory/ped#12

**Comment by Heart-of-N1** [comment]
Created the relevant user guides for the timetable function.
